import {StyleSheet} from 'react-native';

const styles=StyleSheet.create({
    container:{
        flex:1,
        alignItems:'center'
    },
    bgImage:{
        alignItems:'center',
        height:'100%',
        width:'100%'
    },
    header:{
        marginTop:50
    },
    logo:{
        width:160,
        height:70
    },
    judul:{
        marginTop:10,
        color:'white',
        fontSize:30,
        textShadowColor:'black',
        textShadowOffset:{height:2,width:2},
        textShadowRadius:2
    },
    main:{
        marginTop:20,
        alignItems:'center'
    },
    textMain:{
        color:'white'
    },
    tiMain:{
        marginTop:10,
        marginBottom:10,
        padding:5,
        color:'black',
        borderWidth:1,
        backgroundColor:'white',
        height:35,
        width:160,
        textAlign:'center'
    },
    button:{
        color:'white'
    },
    footer:{
        marginTop:10,
        flexDirection:'row'
    },
    push:{
        height:50,
        width:50
    }
})

export {styles};